### ISSUE TITLE
Weird response from request in Grafana

### ISSUE THREAD

**Issue by Frepke** [pdreker/fritzbox_exporter#51]
I'm running fritzexporter in an docker container,
Connected successfully the Prometheus database to the container but Grafana doesn't show anything.
I modified a label in Grafana so it matches a line in the query, but the response is weird (at least for me)

don't know what's wrong

![afbeelding](https://user-images.githubusercontent.com/6153559/114179945-e7731380-993f-11eb-840d-56a07fdfb3b5.png)

**Comment by pdreker** [comment]
Where is that screenshot from? Is that from grafana?

If it is from grafana, this looks like you have connected grafana directly to the exporter instead of connecting to prometheus.

The data flow is (exporter) -> (prometheus) <--> (grafana)

The "weird output" you are seeing is the exporter output, which is not intended to be delivered to grafana directly.

**Comment by Frepke** [comment]
thanks, that's the way I've tried 😔
now I only have to figure out how to connect this to prometheus

**Comment by pdreker** [comment]
Just add a datasource to Graugans and point it to the name of your Prometheus (usually the name of the Container, but that can depend on your setup).

That part is actually quite "straight forward" (but well that my everyday business, so I may be biased)

Best of luck to you!

**Comment by Frepke** [comment]
> Just add a datasource to Grafana and point it to the name of your Prometheus (usually the name of the Container, but that can depend on your setup).
> 
> That part is actually quite "straight forward" (but well that my everyday business, so I may be biased)
> 
> Best of luck to you!

Thanks for your quick replys and help 👍 .
